### PR TITLE
Add zh-TW locale in translate.py

### PR DESCRIPTION
**Pull request by PeterDaveHello**
It'd be great to have Traditional Chinese here, though I'm not sure if this is enough for OpenAI to handle the phrases, or need more prompts to make sure it can recognize the difference.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Oh, got it, I thought OpenAI and DeepL are using in the same time, DeepL indeed only supports Simplified Chinese, so we need to wait for #12, right?

**Comment by anaclumos** [comment]
Certainly. However, the issue lies in the fact that my internal testing has revealed GPT-4 to be excessively costly. At present, I am expending approximately $50 per day to cover the existing regions, but the expenses associated with GPT-4 will be several times higher than that. Therefore, we must first come up with a financially feasible solution to sustain our operations.

**Comment by PeterDaveHello** [comment]
Any chance to share the breakdown of the costs? Just wondering which part cost the most and if it can be optimized.

**Comment by anaclumos** [comment]
Translations account for around 90% of the expenses. While the summarization feature, powered by GPT-3.5, performs exceptionally well for English, it tends to produce inaccurate results when dealing with other languages, especially non-Latin ones. This is particularly challenging for Korean (my language) and Taiwanese (your language).

I conducted an internal benchmark test using GPT-4, but the costs remained unchanged. As someone who holds Taiwan dear, I have considered adding individual Taiwanese support. However, my ultimate goal is to have a finely-tuned LLM for translation purposes, which can be run locally and eliminate costs.

**Comment by PeterDaveHello** [comment]
Thanks for the sharing! CJK issue is always challenging 😅 I was not aware of the cost of translation would be so significant here though!

**Comment by anaclumos** [comment]
@PeterDaveHello Seems like Min Nan Chinese or Hokkien "nan"

**Comment by anaclumos** [comment]
Ref: [Project Linguine @ Sunghyun Cho](https://cho.sh/r/C1CF90)

**Comment by anaclumos** [comment]
https://github.com/anaclumos/heimdall/blob/84f75ef43d7fba2bd78c33f1a68816542a08c8d3/web/src/i18n.ts#L57

**Comment by PeterDaveHello** [comment]
hmmm ... That'll be different, Traditional Chinese is still Chinese 😅

**Comment by anaclumos** [comment]
@PeterDaveHello Oh? Does `zh-TW` refer to multiple things? Could you kindly provide the ISO 639-3 code for the locale you want?

**Comment by anaclumos** [comment]
Also, how different if `zh-HK` from `zh-TW`?

**Comment by PeterDaveHello** [comment]
I'm not familiar with ISO 639-3, but looks like it doesn't distinguish different variations of Chinese language?

**Comment by PeterDaveHello** [comment]
The `zh` in `zh-HK` & `zh-TW` means Chinese, which seems to be defined in `ISO 639-1`. `HK` and `TW` is the country code seem to be defined in `ISO 3166-1`, means Hong Kong and Taiwan. Just like `en-US` and `en-UK`, they are both English, but in the different region, the language can be very different.

**Comment by anaclumos** [comment]
I see your concern. I am fairly sure that zh-TW is the Traditional Chinese mainly used in Taiwan.

**Comment by anaclumos** [comment]
https://cho.sh/r/C1CF90

Also, I have come up with the complete list of locals I will support, so I hope everyone is happy now☺️

**Comment by PeterDaveHello** [comment]
@anaclumos will zh-tw support also be listed on https://hn.cho.sh/?

**Comment by anaclumos** [comment]
@PeterDaveHello In the end, yes. I'm working on v2 for this service, with much delicate language support.

**Comment by anaclumos** [comment]
I expect other languages to arrive by the end of July.

**Comment by PeterDaveHello** [comment]
Got it, thanks again!

**Comment by anaclumos** [comment]
Is this the correct locale that you wanted?

Linguine Engine 結合 Google Translate、Azure Translate、DeepL 翻譯 150+ 種語言，覆蓋全球 99.9% 的受眾。

https://cho.sh/r/6AF7F7

**Comment by PeterDaveHello** [comment]
Looks so, may need longer and source string to be more precisely, but so far so good 👍

**Comment by anaclumos** [comment]
Heimdall Engine is nigh!

Would you want to alpha-test `zh-TW`? If so, please let me know with the options:

- email
- how often do you want to receive it?
  - For example Every day, at 2 PM Taiwan Time, or Every Monday, at 6 AM Pacific Time

**Comment by PeterDaveHello** [comment]
@anaclumos sure, thanks for the invitation! Daily 2 PM would be good for me, please use `heimdall` [at] `peterhsu`.`tw` 🤩

**Comment by PeterDaveHello** [comment]
@anaclumos just let you know that I did receive that mail about 3 days ago, the title is about Rust/JVM, but I received it twice, and no more other mails.

About the result of the translation, it looks like at least the characters are all in Traditional Chinese, and some of the terms are still in Simplified Chinese form, but it's at least something. From what I know, even GPT-4 can't handle it very properly with just basic prompts 😅

**Comment by anaclumos** [comment]
It's here. Working on a new website & subscription form, but you can do it right now here. https://newsletters.cho.sh/subscription/form

**Comment by PeterDaveHello** [comment]
Cool! Not sure if it's intended to select all lists by default? I'm sure I'm not capable of speaking such languages, that might even waste your resource/money even more?

**Comment by anaclumos** [comment]
That’s because it’s a temporary form. The real one is at https://hn.cho.sh 😃

And no, it doesn’t cost me more money even though you sub to all! Maybe couple more pennies? ☺️

**Comment by PeterDaveHello** [comment]
Oh, got it, will use the real one then!

**Comment by PeterDaveHello** [comment]
@anaclumos, the GPT-4 Turbo model is no longer that expensive! Is that something still on the plan that you'd like to use? https://openai.com/pricing

**Comment by anaclumos** [comment]
@PeterDaveHello I tried to use it, but the GPT-4 Turbo is rate-limited at the moment. I'll continue to use GPT-4 until the rate limit loosens. Thanks for the suggestion though!

**Comment by PeterDaveHello** [comment]
@anaclumos just to confirm, it's not yet applied for Traditional Chinese, right?

BTW, what's your user tier?

**Comment by anaclumos** [comment]
@PeterDaveHello I supported traditional Chinese since July! https://hn.cho.sh/zh-Hant/

My user tier is 4 I think

**Comment by PeterDaveHello** [comment]
> @PeterDaveHello I supported traditional Chinese since July! [hn.cho.sh/zh-Hant](https://hn.cho.sh/zh-Hant/)
I mean but it's not powered by GPT-4, is it?

**Comment by PeterDaveHello** [comment]
> My user tier is 4 I think

Tier 4 looks good :+1: because there's no TPD, only TPM, and it's basically the highest tier for gpt series models:

https://platform.openai.com/docs/guides/rate-limits/usage-tiers?context=tier-four

Looking forward to have the increased limited :)

> * The models gpt-4-1106-preview and gpt-4-vision-preview are currently under preview with restrictive rate limits that make them suitable for testing and evaluations, but not for production usage. We plan to increase these limits gradually in the coming weeks with an intention to match current gpt-4 rate limits once the models graduate from preview. As these models are adopted for production workloads we expect latency to increase modestly compared to this preview phase.

**Comment by PeterDaveHello** [comment]
Is GPT-4 still the most costly part of the entire project? I'm curious about the current cost breakdown of the whole project and how I might be able to help. However, for the summarization and analysis part of the articles, switching to GPT-4 Turbo as soon as possible should help, as there will be a significant price difference.

**Comment by PeterDaveHello** [comment]
> GPT-4 Turbo Preview currently has a rate limit of 20 requests per minute and 100 requests per day, which is way too little for any production-level app.

@anaclumos the TPD limit seems to be gone, and the TPM(600,000) is even higher than the original GPT-4(300,000) now :tada: 

image

https://platform.openai.com/docs/guides/rate-limits/usage-tiers?context=tier-four

**Comment by anaclumos** [comment]
Will work on it, it's now under the name of Project [Naroo](https://naroo.ai/zh-Hant).

**Comment by PeterDaveHello** [comment]
It seems to be still working in progress? Looking forward to try it when it's ready 👍

**Comment by anaclumos** [comment]
Already using it!

https://github.com/anaclumos/heimdall/commit/e2dcb57b800e6ce3e729776e46cb22df08975a7c

**Comment by anaclumos** [comment]
Ohhhh... I get what you mean. DeepL, not GPT-4o, handles the translation part. GPT-4o only handles the initial English context generation part. I do think it'll be beneficial to move the translation to GPT-4o tho.

**Comment by PeterDaveHello** [comment]
Oh, okay, that makes sense. Just DeepL can't handle Traditional Chinese, GPT-4 serious may still be the most powerful tool to help Traditional Chinese 😆

**Comment by anaclumos** [comment]
@PeterDaveHello Heimdall now translates using GPT-4o, starting tomorrow. Please check the quality.

**Comment by PeterDaveHello** [comment]
@anaclumos I checked the new translated context, and it's obviously improved.

Actually, I'm not sure if I fully understand the new approach. Is it using different prompts in different languages to generate the context in different languages? From what I know, the translated prompt might not lead to a better result, but using relatively precise English prompts to(or at least try to) control the LLM model could lead to a better result. Also, I'd like to help improve the prompt, that a single version of it might be more efficient, though we sure can just improve the Traditional Chinese version very precisely, but it'll also be great if all languages can benefit from it.

**Comment by anaclumos** [comment]
sounds great. please replace the current prompt with inline string to experiment.

the reason i used multilingual prompts was because sometimes GPT will prepend "OK, here is the Traditional Chinese translations" or sometimes "Sorry, I cannot speak Hindi" or things like that.

that's a bygone era of GPT-3.5 tho, maybe it's different these days.

excited to check improved results!

**Comment by PeterDaveHello** [comment]
The mentioned issue should already be improved and even resolved by using prompts like "Directly give me the result without any additional explanation." So you could consider summarizing in English at once and using an English prompt to translate them to different target languages. This could also save some tokens, I suppose.

**Comment by PeterDaveHello** [comment]
@anaclumos, If we want to improve the Traditional Chinese prompt, should we update at least `CREATE_BULLETPOINT_SUMMARY`/`CREATE_TITLE`, or `YOU_MUST_WRITE_IN`? Not sure which one you'll prefer.

**Comment by anaclumos** [comment]
Please try whatever you want. Let's just observe how the LLM reacts.

**Comment by PeterDaveHello** [comment]
Separating the prompt into multiple parts looks a bit complex, so the most straightforward method to revise the prompts right now is to modify the common `YOU_MUST_WRITE_IN` part; I'll try.

Please also don't mind that I treat the zh-Hant as Traditional Chinese usage in Taiwan, which is obviously using different terms than Simplified Chinese in mainland China.

**Comment by PeterDaveHello** [comment]
#68 sent, thanks.

BTW, to maintain consistency, the prompt is still using Traditional Chinese. If the result is good enough, besides the Simplified Chinese and Traditional Chinese issue, most of the prompts can be just adopted and used for all the languages ;)

**Comment by anaclumos** [comment]
@PeterDaveHello This is the result with your new prompt. Is it better? Good to merge? 

---

## [在我爸爸去世後，我接管並賣掉了他的公司(2018年)](https://anandsanwal.me/2018/06/19/dad-company-sale/)

- 在父親去世後，作者接管了位於印度納西克的一家化學製造公司，同時也管理他的科技公司CB Insights，並最終於2018年6月1日出售了該公司。
- 儘管缺乏行業經驗，作者仍然帶領亞特拉斯精細化工(後來的 AIMS Impex)達到最佳營收年，並創下單月出貨 100 噸的里程碑。
- 關鍵的經驗教訓包括在併購中設定明確目標的重要性、科技與製造業之間的差異，以及科技在簡化業務流程方面的潛力。

### [反應](https://news.ycombinator.com/item?id=40758767)

- 作者分享了一個關於在2018年經營並出售其父親公司的個人故事，強調了在印度管理小型企業的挑戰以及員工關懷的重要性。
- 這篇文章提供了化學工業的見解，特別是香草豆、香草醛和香豆素之間的差異，並強調香豆素不能直接替代。
- 這篇敘述透過探討家族企業的複雜性和突如其來的失落所帶來的影響，引起了讀者的共鳴，使其在作者網站上其他不那麼引人注目的文章中脫穎而出。

## [Andrew S. Tanenbaum 獲得 ACM 軟體系統獎](https://vu.nl/en/news/2024/andrew-s-tanenbaum-receives-acm-software-system-award)

- 2024年6月20日，Andrew S. Tanenbaum 因其在 MINIX(一種基於微核心的 UNIX 作業系統)上的工作，獲得了 ACM 軟體系統獎。
- MINIX 於 1987 年創建，對操作系統的教學以及像 Linux 這樣的系統設計產生了重大影響。如今，Linux 驅動著雲端伺服器、行動電話和物聯網裝置。
- 該獎項由 IBM 贊助，包含 35,000 美元的獎金，並表彰 Tanenbaum 在微內核設計及其對現代作業系統發展的貢獻。

### [反應](https://news.ycombinator.com/item?id=40759277)

- Andrew S. Tanenbaum 獲得了 ACM 軟體系統獎，以表彰他對計算機科學的重大貢獻，特別是通過他具有影響力的教科書和 MINIX 作業系統的開發。
- 「Tanenbaum 的工作對業界產生了持久的影響，他的教科書在計算機科學教育中被廣泛使用，而他的 MINIX 作業系統也影響了其他系統的發展，包括 Linux。」
- 該獎項突顯了Tanenbaum的角色，不僅作為一名軟體開發者，還是一位教育者，他使複雜的計算機科學概念變得易於理解且引人入勝，對學生和專業人士皆是如此。

## [Ruby：一個適合撰寫 Shell 腳本的優秀語言](https://lucasoshiro.github.io/posts-en/2024-06-17-ruby-shellscript/)

- Ruby，經常被其框架 Rails 所掩蓋，實際上是一種撰寫複雜 Shell 腳本的優秀語言。
- 使 Ruby 適合用於 Shell 腳本的主要特點包括簡單的外部命令調用、內建的正則表達式、物件導向類型、函數操作、簡單的執行緒處理，以及內建的檔案和目錄操作。
- 該文章建議在進行複雜的 shell 腳本任務時，考慮使用 Ruby 而非 Bash、Python、Perl 和 JavaScript，因為 Ruby 更加完整且易於使用。

### [反應](https://news.ycombinator.com/item?id=40763640)

- Ruby 提供可讀性高的語法和平滑的複雜度增長，使其成為 Shell 腳本編寫的強力候選者。
- 儘管 Ruby 有其優勢，但它並不廣泛用於 Shell 腳本，因為它不像 Bash 和 Python 那樣預先安裝在大多數系統上。
- 「由於 Perl 在部署上的便利性以及 Go 在創建單一靜態二進位檔方面的優勢，進一步限制了 Ruby 在 Shell 腳本中的採用。」

**Comment by PeterDaveHello** [comment]
@anaclumos I guess so (as no direct comparison exists, but it looks getting better than before)

**Comment by PeterDaveHello** [comment]
@anaclumos the result is really improved!! Thanks!!

**Pull request closed without merging**
